spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.178.160.50:3306/student?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: Liu18365432303.
  thymeleaf:
    cache: false # 去除缓存
    suffix: .html
    mode: HTML5
    encoding: UTF-8
