spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prevention?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: "123456"
  thymeleaf:
    cache: false # 去除缓存
    suffix: .html
    mode: HTML5
    encoding: UTF-8
